#pragma config(Sensor, S1,     sensorColorMid, sensorEV3_Color)
#pragma config(Sensor, S2,     sensorColorRight, sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     sensorColorLeft, sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "colors.h"
#include "colors.c"

#define STATE_DEFAULT 0
#define STATE_TURN_LEFT 1
#define STATE_TURN_RIGHT 2
#define STATE_END -1

#define SPEED_STRAIGHT 30
#define SPEED_TURN 20

TLegoColors lastLeftColor;
TLegoColors lastRightColor;

int currentState = STATE_DEFAULT;

// predefined methods
void stateDefault();
void stateTurnLeft();
void stateTurnRight();

void stateDefault()
{
		TLegoColors colorLeft = getColorNameByHSB(sensorColorLeft, 2);
		TLegoColors colorRight = getColorNameByHSB(sensorColorRight, 3);


		if (colorLeft == colorWhite
			&& colorRight == colorWhite)
		{
			// drive straight
			displayTextLine(4, "2 white");
			setMotorSync(left, right, 0, SPEED_STRAIGHT);
		}
		else if(colorLeft == colorWhite
			&& colorRight == colorBlack)
		{
			displayTextLine(4, "2 black");

			if(lastRightColor == colorBlack && lastLeftColor != colorBlack)
				setMotorSync(left, right, 100, SPEED_TURN);
			else if( lastRightColor != colorBlack && lastLeftColor == colorBlack)
				setMotorSync(left, right, -100, SPEED_TURN);
			else
				setMotorSync(left,right, 0, SPEED_STRAIGHT);
		}
		else if (colorLeft == colorGreen)
		{
			// turn left 90 degrees
			//currentState = STATE_TURN_LEFT;
		}
		else if (colorRight == colorGreen)
		{
			// turn right 90 degrees
			//currentState = STATE_TURN_RIGHT;
		}
		else if (colorLeft == colorBlack)
		{
			// turn right
			displayTextLine(4, "LeftBlack");
			setMotorSync(left, right, -100, SPEED_TURN);
		}
		else if (colorRight == colorBlack)
		{
			// turn left
			displayTextLine(4, "RightBlack");
			setMotorSync(left, right, 100, SPEED_TURN);
		}

		lastLeftColor = colorLeft;
		lastRightColor = colorRight;

}

void stateTurnLeft()
{
	// Move the center of the robot to the mid of the crossing.
	setMotorSyncEncoder(left, right, 0, 125, SPEED_STRAIGHT);
	while (getMotorRunning(left) != 0)
		displayString(4, "Left encoder: %d", getMotorEncoder(left));

	// Turn left.
	setMotorSyncEncoder(left, right, -100, 535, SPEED_TURN);
	while (getMotorRunning(left) != 0)
		displayString(4, "Left encoder: %d", getMotorEncoder(left));

	// Drive off the crossing.
	setMotorSyncEncoder(left, right, 0, 70, SPEED_STRAIGHT);
	while (getMotorRunning(left) != 0)
		displayString(4, "Left encoder: %d", getMotorEncoder(left));

	currentState = STATE_DEFAULT;
}

void stateTurnRight()
{

}

task main()
{
	bool run = true;
	while (run)
	{
		switch (currentState)
		{
			case STATE_DEFAULT:
				stateDefault();
				break;

			case STATE_TURN_LEFT:
				stateTurnLeft();
				break;

			case STATE_TURN_RIGHT:
				stateTurnRight();
				break;

			case STATE_END:
				run = false;
				break;
		}
	}
}
